/*
 * Image data for sprite_bird3.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_bird3_data[];
extern uint16_t sprite_bird3_width;
extern uint16_t sprite_bird3_height;
