/*
 * Image data for sprite_moon.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_moon_data[];
extern uint16_t sprite_moon_width;
extern uint16_t sprite_moon_height;
