/*
 * Image data for sprite_bird1.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_bird1_data[];
extern uint16_t sprite_bird1_width;
extern uint16_t sprite_bird1_height;
