/*
 * Image data for sprite_cloudr.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_cloudr_data[];
extern uint16_t sprite_cloudr_width;
extern uint16_t sprite_cloudr_height;
