/*
 * Image data for sprite_sun.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_sun_data[];
extern uint16_t sprite_sun_width;
extern uint16_t sprite_sun_height;
