/*
 * Image data for sprite_cloudl.png
 * This file was automatically generated by pv_image.py
 * DO NOT EDIT THIS FILE!
 */
 
#include <stdint.h>

extern uint16_t sprite_cloudl_data[];
extern uint16_t sprite_cloudl_width;
extern uint16_t sprite_cloudl_height;
